namespace FFmpeg.Logging;

/// <summary>
/// Specifies additional formatting options for FFmpeg log messages.
/// </summary>
/// <remarks>
/// These flags control how log messages are formatted when using FFmpeg's
/// logging facilities. Multiple values can be combined.
/// </remarks>
[Flags]
public enum LogFlags
{
    /// <summary>
    /// Suppresses repeated log messages by collapsing consecutive identical
    /// messages into a single summary entry.
    /// </summary>
    /// <remarks>
    /// This flag is effective only when logging is performed through FFmpeg's
    /// <c>av_log()</c> API. Applications that write directly to standard output
    /// or standard error will not benefit from repeated message suppression.
    /// </remarks>
    SkipRepeated = ffmpeg.AV_LOG_SKIP_REPEATED,

    /// <summary>
    /// Prefixes each log message with the current system date and time.
    /// </summary>
    PrintDateTime = ffmpeg.AV_LOG_PRINT_DATETIME,

    /// <summary>
    /// Includes the log level in messages generated by FFmpeg components.
    /// </summary>
    /// <remarks>
    /// For example:
    /// <c>[rawvideo @ 0xDEADBEEF][error] encode did not produce valid pts</c>.
    /// </remarks>
    PrintLogLevel = ffmpeg.AV_LOG_PRINT_LEVEL,

    /// <summary>
    /// Prefixes each log message with the current system time.
    /// </summary>
    PrintTime = ffmpeg.AV_LOG_PRINT_TIME,
}
