namespace FFmpeg.Logging;

/// <summary>
/// Specifies the severity level of messages generated by FFmpeg.
/// </summary>
/// <remarks>
/// Log levels determine which messages are emitted by FFmpeg's logging system.
/// Lower-severity messages provide more diagnostic information, while higher
/// severities indicate increasingly serious conditions.
/// </remarks>
public enum LogLevel
{
    /// <summary>
    /// Disables all logging output.
    /// </summary>
    Quiet = ffmpeg.AV_LOG_QUIET,

    /// <summary>
    /// Logs fatal errors that cause the current operation to fail.
    /// </summary>
    Panic = ffmpeg.AV_LOG_PANIC,

    /// <summary>
    /// Logs unrecoverable errors that typically terminate the application.
    /// </summary>
    Fatal = ffmpeg.AV_LOG_FATAL,

    /// <summary>
    /// Logs recoverable errors that prevent the requested operation from completing.
    /// </summary>
    Error = ffmpeg.AV_LOG_ERROR,

    /// <summary>
    /// Logs warnings about unexpected conditions that do not prevent continued operation.
    /// </summary>
    Warning = ffmpeg.AV_LOG_WARNING,

    /// <summary>
    /// Logs informational messages about normal operation.
    /// </summary>
    Info = ffmpeg.AV_LOG_INFO,

    /// <summary>
    /// Logs additional diagnostic information.
    /// </summary>
    Verbose = ffmpeg.AV_LOG_VERBOSE,

    /// <summary>
    /// Logs detailed debugging information intended for developers.
    /// </summary>
    Debug = ffmpeg.AV_LOG_DEBUG,

    /// <summary>
    /// Logs highly detailed tracing information.
    /// </summary>
    Trace = ffmpeg.AV_LOG_TRACE,
}
