<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="FFmpegDotNet.bin.winx64" Version="8.0.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.0.1" />
		<PackageReference Include="MSTest.TestFramework" Version="4.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FFmpeg\FFmpeg.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Test-Files\10s-11s.f32le.pcm">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Test-Files\10s-11s.s16le.pcm">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Test-Files\mp4-example-video-download-full-hd-1920x1080.1min.mp4">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Test-Files\mp4-example-video-download-full-hd-1920x1080.1min.mp4.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Test-Files\n123.bgra">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Test-Files\n123.yuv">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
